//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewBank.Dominio.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Lingua {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Lingua() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NewBank.Dominio.Resources.Lingua", typeof(Lingua).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foi criada com sucesso!.
        /// </summary>
        public static string AddRespP2 {
            get {
                return ResourceManager.GetString("AddRespP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso.
        /// </summary>
        public static string Aviso {
            get {
                return ResourceManager.GetString("Aviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cadastrar uma conta.
        /// </summary>
        public static string CadConta {
            get {
                return ResourceManager.GetString("CadConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelar.
        /// </summary>
        public static string Cancelar {
            get {
                return ResourceManager.GetString("Cancelar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmar Exclusão.
        /// </summary>
        public static string ConfirmarExclusao {
            get {
                return ResourceManager.GetString("ConfirmarExclusao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta Corrente.
        /// </summary>
        public static string ContaCorrente {
            get {
                return ResourceManager.GetString("ContaCorrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta Poupança.
        /// </summary>
        public static string ContaPoupanca {
            get {
                return ResourceManager.GetString("ContaPoupanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta Salario.
        /// </summary>
        public static string ContaSalario {
            get {
                return ResourceManager.GetString("ContaSalario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrente.
        /// </summary>
        public static string Corrente {
            get {
                return ResourceManager.GetString("Corrente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta Salario.
        /// </summary>
        public static string CotaSalario {
            get {
                return ResourceManager.GetString("CotaSalario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depositar.
        /// </summary>
        public static string Depositar {
            get {
                return ResourceManager.GetString("Depositar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição.
        /// </summary>
        public static string Descricao {
            get {
                return ResourceManager.GetString("Descricao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foi editada com sucesso!.
        /// </summary>
        public static string EditRespP2 {
            get {
                return ResourceManager.GetString("EditRespP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editar uma conta.
        /// </summary>
        public static string EdtConta {
            get {
                return ResourceManager.GetString("EdtConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingles.
        /// </summary>
        public static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Endereço.
        /// </summary>
        public static string Endereco {
            get {
                return ResourceManager.GetString("Endereco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluir uma conta.
        /// </summary>
        public static string ExcConta {
            get {
                return ResourceManager.GetString("ExcConta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foi excluida com sucesso!.
        /// </summary>
        public static string ExRespP2 {
            get {
                return ResourceManager.GetString("ExRespP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrato.
        /// </summary>
        public static string Extrato {
            get {
                return ResourceManager.GetString("Extrato", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O extrato foi criado com sucesso! no local.
        /// </summary>
        public static string ExtratoAvisoSuces {
            get {
                return ResourceManager.GetString("ExtratoAvisoSuces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extrato das contas do titular.
        /// </summary>
        public static string ExtratoPdf {
            get {
                return ResourceManager.GetString("ExtratoPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Francês.
        /// </summary>
        public static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerar pdf.
        /// </summary>
        public static string GerarPdf {
            get {
                return ResourceManager.GetString("GerarPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gravar.
        /// </summary>
        public static string Gravar {
            get {
                return ResourceManager.GetString("Gravar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historioco.
        /// </summary>
        public static string Historioco {
            get {
                return ResourceManager.GetString("Historioco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite.
        /// </summary>
        public static string Limite {
            get {
                return ResourceManager.GetString("Limite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta.
        /// </summary>
        public static string MenuContas {
            get {
                return ResourceManager.GetString("MenuContas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lingua.
        /// </summary>
        public static string MenuLingua {
            get {
                return ResourceManager.GetString("MenuLingua", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opção.
        /// </summary>
        public static string MenuOpcao {
            get {
                return ResourceManager.GetString("MenuOpcao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Nome {
            get {
                return ResourceManager.GetString("Nome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possivel realiza a operação.
        /// </summary>
        public static string NPssOpera {
            get {
                return ResourceManager.GetString("NPssOpera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Num. Conta.
        /// </summary>
        public static string Numero {
            get {
                return ResourceManager.GetString("Numero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operação.
        /// </summary>
        public static string Operacao {
            get {
                return ResourceManager.GetString("Operacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A operação foi realizado com sucesso.
        /// </summary>
        public static string OperacaoSucesso {
            get {
                return ResourceManager.GetString("OperacaoSucesso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagar Online.
        /// </summary>
        public static string PagarOnline {
            get {
                return ResourceManager.GetString("PagarOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você deseja realmente excluir a conta numero:.
        /// </summary>
        public static string PerguntaExcluir {
            get {
                return ResourceManager.GetString("PerguntaExcluir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poupança.
        /// </summary>
        public static string Poupanca {
            get {
                return ResourceManager.GetString("Poupanca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portugues.
        /// </summary>
        public static string pt {
            get {
                return ResourceManager.GetString("pt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta numero:.
        /// </summary>
        public static string Resp1 {
            get {
                return ResourceManager.GetString("Resp1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sacar.
        /// </summary>
        public static string Sacar {
            get {
                return ResourceManager.GetString("Sacar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salario.
        /// </summary>
        public static string Salario {
            get {
                return ResourceManager.GetString("Salario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo.
        /// </summary>
        public static string Saldo {
            get {
                return ResourceManager.GetString("Saldo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saldo atual.
        /// </summary>
        public static string SaldoFim {
            get {
                return ResourceManager.GetString("SaldoFim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é possível realizar esta ação sem uma conta selecionada..
        /// </summary>
        public static string SelecionarAviso {
            get {
                return ResourceManager.GetString("SelecionarAviso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taxa.
        /// </summary>
        public static string Taxa {
            get {
                return ResourceManager.GetString("Taxa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titular.
        /// </summary>
        public static string Titular {
            get {
                return ResourceManager.GetString("Titular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor.
        /// </summary>
        public static string Valor {
            get {
                return ResourceManager.GetString("Valor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltar.
        /// </summary>
        public static string Voltar {
            get {
                return ResourceManager.GetString("Voltar", resourceCulture);
            }
        }
    }
}
